version: '3'

tasks:
  default:
    deps:
      - build

  build:
    silent: true
    cmds:
      - echo "building project"
      - go build -o build/bin/main ./internal/api/cmd
      - echo "project compiled successfully"

  start:
    deps:
      - build
    cmd: ./build/bin/main

  start:dev:
    description: Start the application in watch mode
    silent: true
    cmd: air
